services:
  postgres:
    image: postgres
    container_name: bookcatalog-postgres-dev
    environment:
      POSTGRES_DB: BookCatalogDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d BookCatalogDb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data: